#!/bin/bash

# Script to run Leader-Follower locally for testing
# This script helps you start all nodes in separate terminals

echo "=========================================="
echo "Leader-Follower Local Testing Guide"
echo "=========================================="
echo ""
echo "To test Leader-Follower mode, open 6 terminals:"
echo ""
echo "Terminal 1 (Leader - W=5, R=1):"
echo "  cd leader-follower"
echo "  NODE_TYPE=leader W=5 R=1 PORT=8080 FOLLOWER_URLS=http://localhost:8081,http://localhost:8082,http://localhost:8083,http://localhost:8084 go run ."
echo ""
echo "Terminal 2 (Follower 1):"
echo "  cd leader-follower"
echo "  NODE_TYPE=follower PORT=8081 go run ."
echo ""
echo "Terminal 3 (Follower 2):"
echo "  cd leader-follower"
echo "  NODE_TYPE=follower PORT=8082 go run ."
echo ""
echo "Terminal 4 (Follower 3):"
echo "  cd leader-follower"
echo "  NODE_TYPE=follower PORT=8083 go run ."
echo ""
echo "Terminal 5 (Follower 4):"
echo "  cd leader-follower"
echo "  NODE_TYPE=follower PORT=8084 go run ."
echo ""
echo "Terminal 6 (Run Tests):"
echo "  cd tests"
echo "  go run leader_follower_test.go"
echo ""
echo "=========================================="
echo "Alternative W/R Configurations:"
echo "=========================================="
echo ""
echo "W=1, R=5 (Fast writes, consistent reads):"
echo "  NODE_TYPE=leader W=1 R=5 PORT=8080 FOLLOWER_URLS=http://localhost:8081,http://localhost:8082,http://localhost:8083,http://localhost:8084 go run ."
echo ""
echo "W=3, R=3 (Quorum):"
echo "  NODE_TYPE=leader W=3 R=3 PORT=8080 FOLLOWER_URLS=http://localhost:8081,http://localhost:8082,http://localhost:8083,http://localhost:8084 go run ."
echo ""
echo "=========================================="
echo "Quick API Test:"
echo "=========================================="
echo ""
echo "Write:"
echo "  curl -X POST http://localhost:8080/set -H 'Content-Type: application/json' -d '{\"key\":\"test\",\"value\":\"hello\"}'"
echo ""
echo "Read:"
echo "  curl http://localhost:8080/get/test"
echo ""
echo "Local Read (for testing):"
echo "  curl http://localhost:8081/local_read/test"
echo ""
