#!/bin/bash

# Script to run Leaderless locally for testing
# This script helps you start all nodes in separate terminals

echo "=========================================="
echo "Leaderless Local Testing Guide"
echo "=========================================="
echo ""
echo "To test Leaderless mode, open 6 terminals:"
echo ""
echo "Terminal 1 (Node 1):"
echo "  cd leaderless"
echo "  NODE_ID=node1 W=5 R=1 PORT=8080 PEER_URLS=http://localhost:8081,http://localhost:8082,http://localhost:8083,http://localhost:8084 go run ."
echo ""
echo "Terminal 2 (Node 2):"
echo "  cd leaderless"
echo "  NODE_ID=node2 W=5 R=1 PORT=8081 PEER_URLS=http://localhost:8080,http://localhost:8082,http://localhost:8083,http://localhost:8084 go run ."
echo ""
echo "Terminal 3 (Node 3):"
echo "  cd leaderless"
echo "  NODE_ID=node3 W=5 R=1 PORT=8082 PEER_URLS=http://localhost:8080,http://localhost:8081,http://localhost:8083,http://localhost:8084 go run ."
echo ""
echo "Terminal 4 (Node 4):"
echo "  cd leaderless"
echo "  NODE_ID=node4 W=5 R=1 PORT=8083 PEER_URLS=http://localhost:8080,http://localhost:8081,http://localhost:8082,http://localhost:8084 go run ."
echo ""
echo "Terminal 5 (Node 5):"
echo "  cd leaderless"
echo "  NODE_ID=node5 W=5 R=1 PORT=8084 PEER_URLS=http://localhost:8080,http://localhost:8081,http://localhost:8082,http://localhost:8083 go run ."
echo ""
echo "Terminal 6 (Run Tests):"
echo "  cd tests"
echo "  go run leaderless_test.go"
echo ""
echo "=========================================="
echo "Quick API Test:"
echo "=========================================="
echo ""
echo "Write to Node 1:"
echo "  curl -X POST http://localhost:8080/set -H 'Content-Type: application/json' -d '{\"key\":\"test\",\"value\":\"hello\"}'"
echo ""
echo "Read from Node 2:"
echo "  curl http://localhost:8081/get/test"
echo ""
echo "Local Read from Node 3 (for testing):"
echo "  curl http://localhost:8082/local_read/test"
echo ""
echo "Note: With W=5, R=1:"
echo "  - All 5 nodes must acknowledge writes (strong durability)"
echo "  - Reads only query 1 node (may be stale during replication)"
echo ""
